export default {
  dashboard: '/',
  // bras: '/group-mp',
     show:'/group-mp/group-mp-topos',
     group_mp_list:'/group-mp/group-mp-list',
     group_mp_summary:'/group-mp/group-mp-summary',
     parts_of_device:'/group-mp/parts',
  // cgnat: '/cgnat',
     cgnat_prefer:'/cgnat/prefer',
     cgnat_summary:'/cgnat/summary',
  // iplc: '/iplc',
     traffic_statistics:'/iplc/traffic-statistics',
     traffic_chart:'/iplc/traffic-chart',
  // devices: '/devices',
     add_new_device:'/devices/add-new-device',
     remove_ports_logs:'/devices/remove-ports',
     all_devices:'/devices/devices',
     function_list:'/devices/function-list',
     areas_and_rooms:'/devices/areas-and-rooms',
     warehouse:'/devices/warehouse',
  // transit_peering: '/auto-balancing-transit-peering',
     irb_detail:'/auto-balancing-transit-peering/irb-detail',
     graph_flow_history:'/auto-balancing-transit-peering/graph-flow-history',
  // balancing_iplc:'/blancing-iplc',
     ipv6_to_mpop:'/auto-balancing-iplc/ipv6-to-mpop',
     iplc_report:'/auto-balancing-iplc/iplc-report',
     equal_report:'/auto-balancing-iplc/equal-report',
     iplc_mpop_by_gw_ipv6:'/auto-balancing-iplc/iplc-mpop-by-gw-ipv6',
     equal_mpop_by_gw_ipv6:'/auto-balancing-iplc/equal-mpop-by-gw-ipv6',
     iplc_mpop_by_gw_ipv4:'/auto-balancing-iplc/iplc-mpop-by-gw-ipv4',
     equal_mpop_by_gw_ipv4:'/auto-balancing-iplc/equal-mpop-by-gw-ipv4',
  // tool_cgnat:'/tool-cgnat'
     devices_config:'/tool-cgnat/devices_config',
     error_log:'/tool-cgnat/error-log',
     recommend_action:'/tool-cgnat/recommed-action',
     history:'/tool-cgnat/history',
     log_config:'/tool-cgnat/log-config',
     variables_config:'/tool-cgnat/variables-config'
};
